### Libraries and functions importation

In [4]:
import sys
sys.path.append("..")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import sklearn
import xgboost
import lightgbm
import catboost

### EDA

**Preprocessing**

In [5]:
data = pd.read_csv('../data/pf_suvs.csv')

In [6]:
print("\n Dataset ALEATORIO")
print(data.sample(5))

print("\n -------- RESUMEN - ESTADISTICOS E INFO -------- \n" )
print("\n DATA INFO")
print(data.info())
print("\n DATA DESCRIPCION " )
print(data.describe())

 Dataset ALEATORIO
       Unnamed: 0       Marca    Modelo     Año                 Versión  \
16900       16900        Ford  Ecosport  2014.0  1.6 Titanium 110cv 4x2
5404         5404     Peugeot      2008  2018.0           1.6 Thp Sport
3511         3511  Volkswagen   T-Cross  2021.0       1.6 Trendlinde Mt
5812         5812        Ford  Ecosport  2013.0        1.6 Se 110cv 4x2
6559         6559  Volkswagen   T-Cross  2025.0         1.6 Highline At

        Color Tipo de combustible  Puertas Transmisión Motor  \
16900     NaN               Nafta      5.0      Manual   1.6
5404   Marrón               Nafta      5.0      Manual   1.6
3511    Negro               Nafta      5.0      Manual   1.6
5812   Blanco               Nafta      5.0      Manual   1.6
6559   Blanco               Nafta      5.0  Automática   1.6

      Tipo de carrocería Con cámara de retroceso Kilómetros  \
16900                SUV                     NaN   108000.0
5404                 SUV                     NaN    87000.0
3511                 SUV                     NaN    90000.0
5812                 SUV                     NaN   111900.0
6559                 SUV                     NaN        0.0

                                     Título      Precio Moneda  \
16900  Ford Ecosport 1.6 Titanium 110cv 4x2  14900000.0      $
5404             Peugeot 2008 1.6 Thp Sport     14900.0    US$
3511   Volkswagen T-Cross 1.6 Trendlinde Mt  23900000.0      $
5812         Ford Ecosport 1.6 Se 110cv 4x2     13000.0    US$
6559     Volkswagen T-Cross 1.6 Highline At  44000000.0      $

                                             Descripción Tipo de vendedor
16900  FORD ECO SPORT TITUANIUM 2014110 CV 4X2 GUALEG...    concesionaria
5404   Vehículo en excelentes condiciones digno de ve...    concesionaria
3511   T CROSS 2021IMPECABLE PODEMOS FINANCIAR HASTA ...    concesionaria
5812   DMB-AUTOMOTORES# FINANCIAMOS CON ANTICIPO DEL ...    concesionaria
6559   SOMOS AUTOS MEDITERRÁNEOS, tu concesionario of...    concesionaria

 -------- RESUMEN - ESTADISTICOS E INFO --------


 DATA INFO
<class 'pandas.DataFrame'>
RangeIndex: 18254 entries, 0 to 18253
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               18254 non-null  int64
 1   Marca                    18254 non-null  str
 2   Modelo                   18254 non-null  str
 3   Año                      18254 non-null  float64
 4   Versión                  18254 non-null  str
 5   Color                    17865 non-null  str
 6   Tipo de combustible      18254 non-null  str
 7   Puertas                  18254 non-null  float64
 8   Transmisión              18239 non-null  str
 9   Motor                    18216 non-null  str
 10  Tipo de carrocería       18254 non-null  str
 11  Con cámara de retroceso  4691 non-null   str
 12  Kilómetros               18254 non-null  str
 13  Título                   18254 non-null  str
 14  Precio                   18254 non-null  float64
 15  Moneda                   18254 non-null  str
 16  Descripción              18254 non-null  str
 17  Tipo de vendedor         18254 non-null  str
dtypes: float64(3), int64(1), str(14)
memory usage: 2.5 MB
None

 DATA DESCRIPCION
         Unnamed: 0            Año       Puertas        Precio
count  18254.000000   18254.000000  18254.000000  1.825400e+04
mean    9126.500000    2042.796209     18.167306  1.760162e+07
std     5269.620242    3217.260996    891.766121  1.720810e+07
min        0.000000    1981.000000      2.000000  1.110000e+02
25%     4563.250000    2016.000000      5.000000  3.190000e+04
50%     9126.500000    2019.000000      5.000000  1.720000e+07
75%    13689.750000    2024.000000      5.000000  2.995000e+07
max    18253.000000  436694.000000  60252.000000  3.495000e+08

In [7]:
summary = pd.DataFrame({
    "dtype": data.dtypes,
    "nulos": data.isnull().sum(),
    "unicos": data.nunique()
})
summary

                           dtype  nulos  unicos
Unnamed: 0                 int64      0   18254
Marca                        str      0      47
Modelo                       str      0     137
Año                      float64      0      40
Versión                      str      0    2072
Color                        str    389      70
Tipo de combustible          str      0       8
Puertas                  float64      0       7
Transmisión                  str     15       4
Motor                        str     38     271
Tipo de carrocería           str      0       1
Con cámara de retroceso      str  13563       2
Kilómetros                   str      0    2175
Título                       str      0    2220
Precio                   float64      0    2914
Moneda                       str      0       2
Descripción                  str      0   12142
Tipo de vendedor             str      0       3

In [8]:
data.describe()

         Unnamed: 0            Año       Puertas        Precio
count  18254.000000   18254.000000  18254.000000  1.825400e+04
mean    9126.500000    2042.796209     18.167306  1.760162e+07
std     5269.620242    3217.260996    891.766121  1.720810e+07
min        0.000000    1981.000000      2.000000  1.110000e+02
25%     4563.250000    2016.000000      5.000000  3.190000e+04
50%     9126.500000    2019.000000      5.000000  1.720000e+07
75%    13689.750000    2024.000000      5.000000  2.995000e+07
max    18253.000000  436694.000000  60252.000000  3.495000e+08

In [9]:
#Imprimir la cantidad UNICA de elementos por feature
for col in data.columns:
    print(col, data[col].nunique())

Unnamed: 0 18254
Marca 47
Modelo 137
Año 40
Versión 2072
Color 70
Tipo de combustible 8
Puertas 7
Transmisión 4
Motor 271
Tipo de carrocería 1
Con cámara de retroceso 2
Kilómetros 2175
Título 2220
Precio 2914
Moneda 2
Descripción 12142
Tipo de vendedor 3

In [10]:
data["Puertas"].value_counts().sort_index()

Puertas
2.0           10
3.0          105
4.0          399
5.0        17731
6.0            3
7.0            2
60252.0        4
Name: count, dtype: int64

vemos boxplot para outliers y distribucion

In [11]:
num_cols = data.select_dtypes(include=["int64","float64"]).columns
print(num_cols)

Index(['Unnamed: 0', 'Año', 'Puertas', 'Precio'], dtype='str')

**Data Split and Normalize**

### MODELS

### Comparison bewtween models

### Final Model