### Libraries and functions importation

In [ ]:
import sys
sys.path.append("..")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import sklearn
import xgboost
import lightgbm
import catboost

c:\Users\Martina\Desktop\UDESA\TERCERO\Ml DL\Gurevich_Otero_Informe_PF\Gurevich_Otero_Informe_PF\notebook

### EDA

**Preprocessing**

In [7]:
data = pd.read_csv('../data/pf_suvs.csv')

In [8]:
print("\n Dataset ALEATORIO")
print(data.sample(5))

print("\n -------- RESUMEN - ESTADISTICOS E INFO -------- \n" )
print("\n DATA INFO")
print(data.info())
print("\n DATA DESCRIPCION " )
print(data.describe())
print("\n VALORES FALTANTES")
print(data.isna().sum())

 Dataset ALEATORIO
       Unnamed: 0      Marca     Modelo     Año                Versión  \
8763         8763    Citroën  C4 Cactus  2024.0  1.6 Thp 165 Shine At6
1653         1653    Hyundai     Tucson  2012.0        2.0 Gls 6at 4wd
5269         5269     Nissan      Kicks  2019.0        1.6 Advance Cvt
6736         6736  Chevrolet    Tracker  2024.0                1.2T At
17071       17071       Ford  Territory  2022.0               1.5t Sel

        Color Tipo de combustible  Puertas Transmisión Motor  \
8763   Blanco               Nafta      4.0  Automática   1.6
1653   Blanco               Nafta      5.0  Automática   2.0
5269     Gris               Nafta      5.0  Automática   1.6
6736     Azul               Nafta      5.0  Automática   1.2
17071  Blanco               Nafta      5.0  Automática   1.5

      Tipo de carrocería Con cámara de retroceso Kilómetros  \
8763                 SUV                     NaN    10000.0
1653                 SUV                     NaN   160000.0
5269                 SUV                     NaN    99000.0
6736                 SUV                     NaN        0.0
17071                SUV                     NaN    70405.0

                                        Título      Precio Moneda  \
8763   Citroën C4 Cactus 1.6 Thp 165 Shine At6  31599000.0      $
1653            Hyundai Tucson 2.0 Gls 6at 4wd  18500000.0      $
5269              Nissan Kicks 1.6 Advance Cvt     18900.0    US$
6736                 Chevrolet Tracker 1.2T At  32000000.0      $
17071                  Ford Territory 1.5t Sel     31500.0    US$

                                             Descripción Tipo de vendedor
8763   Bienvenidos a AUTOFAMILY, somos una familia di...    concesionaria
1653   El vendedor no incluyó una descripción del pro...    concesionaria
5269   Usado seleccionado:Precio Contado Efectivo: $ ...    concesionaria
6736   Chevrolet Tracker 1.2 LTZ color darkmoon blueA...    concesionaria
17071  PUGLIAAUTOConcesionario Oficial Multim-35 años...    concesionaria

 -------- RESUMEN - ESTADISTICOS E INFO --------


 DATA INFO
<class 'pandas.DataFrame'>
RangeIndex: 18254 entries, 0 to 18253
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               18254 non-null  int64
 1   Marca                    18254 non-null  str
 2   Modelo                   18254 non-null  str
 3   Año                      18254 non-null  float64
 4   Versión                  18254 non-null  str
 5   Color                    17865 non-null  str
 6   Tipo de combustible      18254 non-null  str
 7   Puertas                  18254 non-null  float64
 8   Transmisión              18239 non-null  str
 9   Motor                    18216 non-null  str
 10  Tipo de carrocería       18254 non-null  str
 11  Con cámara de retroceso  4691 non-null   str
 12  Kilómetros               18254 non-null  str
 13  Título                   18254 non-null  str
 14  Precio                   18254 non-null  float64
 15  Moneda                   18254 non-null  str
 16  Descripción              18254 non-null  str
 17  Tipo de vendedor         18254 non-null  str
dtypes: float64(3), int64(1), str(14)
memory usage: 2.5 MB
None

 DATA DESCRIPCION
         Unnamed: 0            Año       Puertas        Precio
count  18254.000000   18254.000000  18254.000000  1.825400e+04
mean    9126.500000    2042.796209     18.167306  1.760162e+07
std     5269.620242    3217.260996    891.766121  1.720810e+07
min        0.000000    1981.000000      2.000000  1.110000e+02
25%     4563.250000    2016.000000      5.000000  3.190000e+04
50%     9126.500000    2019.000000      5.000000  1.720000e+07
75%    13689.750000    2024.000000      5.000000  2.995000e+07
max    18253.000000  436694.000000  60252.000000  3.495000e+08

 VALORES FALTANTES
Unnamed: 0                     0
Marca                          0
Modelo                         0
Año                            0
Versión                        0
Color                        389
Tipo de combustible            0
Puertas                        0
Transmisión                   15
Motor                         38
Tipo de carrocería             0
Con cámara de retroceso    13563
Kilómetros                     0
Título                         0
Precio                         0
Moneda                         0
Descripción                    0
Tipo de vendedor               0
dtype: int64

In [ ]:
summary = pd.DataFrame({
    "dtype": data.dtypes,
    "nulos": data.isnull().sum(),
    "unicos": data.nunique()
})
summary

                           dtype  nulos  unicos
Unnamed: 0                 int64      0   18254
Marca                        str      0      47
Modelo                       str      0     137
Año                      float64      0      40
Versión                      str      0    2072
Color                        str    389      70
Tipo de combustible          str      0       8
Puertas                  float64      0       7
Transmisión                  str     15       4
Motor                        str     38     271
Tipo de carrocería           str      0       1
Con cámara de retroceso      str  13563       2
Kilómetros                   str      0    2175
Título                       str      0    2220
Precio                   float64      0    2914
Moneda                       str      0       2
Descripción                  str      0   12142
Tipo de vendedor             str      0       3

In [19]:
data.describe()

,Unnamed: 0,Año,Puertas,Con cámara de retroceso,Precio
count,18254.000000,18254.000000,18254.000000,18254.000000,1.825400e+04
mean,9126.500000,2042.796209,18.167306,0.818834,1.760162e+07
std,5269.620242,3217.260996,891.766121,0.385166,1.720810e+07
min,0.000000,1981.000000,2.000000,0.000000,1.110000e+02
25%,4563.250000,2016.000000,5.000000,1.000000,3.190000e+04
50%,9126.500000,2019.000000,5.000000,1.000000,1.720000e+07
75%,13689.750000,2024.000000,5.000000,1.000000,2.995000e+07
max,18253.000000,436694.000000,60252.000000,1.000000,3.495000e+08

In [ ]:
#Imprimir la cantidad UNICA de elementos por feature
for col in data.columns:
    print(c, data[col].nunique())

Unnamed: 0 18254
Marca 47
Modelo 137
Año 40
Versión 2072
Color 70
Tipo de combustible 8
Puertas 7
Transmisión 4
Motor 271
Tipo de carrocería 1
Con cámara de retroceso 2
Kilómetros 2175
Título 2220
Precio 2914
Moneda 2
Descripción 12142
Tipo de vendedor 3

ideas para sol el prepro: 
LOs null : 
1. Camara de retroceso  :   Moda * (marca + año)
2. pasar one hot , knn completar ocn KNN IMPUTER
3. motor : BORARR  
4. color:  Moda * (marca + modelo)
 

borrar la unnamed 
hacer col de 0km y usado  
pasaar las monedas todas a usd  y precio logico (ver tipo )y la saco
limpiar SUV 
pasar a 5 puertaas PUERTAS

In [27]:
data["Puertas"].value_counts().sort_index()

Puertas
2.0           10
3.0          105
4.0          399
5.0        17731
6.0            3
7.0            2
60252.0        4
Name: count, dtype: int64

vemos boxplot para outliers y distribucion

In [29]:
num_cols = data.select_dtypes(include=["int64","float64"]).columns

print(num_cols)

Index(['Unnamed: 0', 'Año', 'Puertas', 'Con cámara de retroceso', 'Precio'], dtype='str')

**Data Split and Normalize**

### MODELS

### Comparison bewtween models

### Final Model